// ── Comprehensive World Crop Database ──────────────────────────────────────
// 200+ crops across 9 categories with Indian mandi price references

const CROP_DATA = [

  // ═══════════════════ VEGETABLES ═══════════════════════════════════════════
  { id:  1, name:'Tomato',              emoji:'🍅', category:'Vegetables', price:  32, prevPrice:  28, unit:'kg',      state:'Maharashtra',      market:'Pune APMC'            },
  { id:  2, name:'Onion',               emoji:'🧅', category:'Vegetables', price:  18, prevPrice:  22, unit:'kg',      state:'Maharashtra',      market:'Nashik APMC'          },
  { id:  3, name:'Potato',              emoji:'🥔', category:'Vegetables', price:  15, prevPrice:  14, unit:'kg',      state:'Uttar Pradesh',    market:'Agra Mandi'           },
  { id:  4, name:'Cauliflower',         emoji:'🥦', category:'Vegetables', price:  22, prevPrice:  25, unit:'kg',      state:'Punjab',           market:'Amritsar APMC'        },
  { id:  5, name:'Brinjal (Eggplant)',  emoji:'🍆', category:'Vegetables', price:  18, prevPrice:  14, unit:'kg',      state:'Karnataka',        market:'Bengaluru APMC'       },
  { id:  6, name:'Cucumber',            emoji:'🥒', category:'Vegetables', price:  20, prevPrice:  18, unit:'kg',      state:'Karnataka',        market:'Bengaluru APMC'       },
  { id:  7, name:'Cabbage',             emoji:'🥬', category:'Vegetables', price:  12, prevPrice:  15, unit:'kg',      state:'Tamil Nadu',       market:'Koyambedu APMC'       },
  { id:  8, name:'Spinach',             emoji:'🌿', category:'Vegetables', price:   8, prevPrice:   7, unit:'bunch',   state:'Maharashtra',      market:'Mumbai APMC'          },
  { id:  9, name:'Bitter Gourd',        emoji:'🫑', category:'Vegetables', price:  24, prevPrice:  20, unit:'kg',      state:'Andhra Pradesh',   market:'Vijayawada APMC'      },
  { id: 10, name:'Bottle Gourd',        emoji:'🟢', category:'Vegetables', price:  14, prevPrice:  12, unit:'kg',      state:'Uttar Pradesh',    market:'Lucknow Mandi'        },
  { id: 11, name:'Green Peas',          emoji:'🫛', category:'Vegetables', price:  45, prevPrice:  38, unit:'kg',      state:'Himachal Pradesh', market:'Shimla Mandi'         },
  { id: 12, name:'Carrot',              emoji:'🥕', category:'Vegetables', price:  28, prevPrice:  32, unit:'kg',      state:'Punjab',           market:'Ludhiana Mandi'       },
  { id: 13, name:'Beetroot',            emoji:'🔴', category:'Vegetables', price:  20, prevPrice:  18, unit:'kg',      state:'Andhra Pradesh',   market:'Tirupati APMC'        },
  { id: 14, name:'Garlic',              emoji:'🧄', category:'Vegetables', price:  90, prevPrice:  80, unit:'kg',      state:'Madhya Pradesh',   market:'Mandsaur Mandi'       },
  { id: 15, name:'Capsicum',            emoji:'🫑', category:'Vegetables', price:  35, prevPrice:  30, unit:'kg',      state:'Karnataka',        market:'Bengaluru APMC'       },
  { id: 16, name:'Lady Finger (Okra)',  emoji:'💚', category:'Vegetables', price:  22, prevPrice:  18, unit:'kg',      state:'Gujarat',          market:'Ahmedabad APMC'       },
  { id: 17, name:'Pumpkin',             emoji:'🎃', category:'Vegetables', price:  12, prevPrice:  10, unit:'kg',      state:'Rajasthan',        market:'Jaipur Mandi'         },
  { id: 18, name:'Ridge Gourd',         emoji:'🟩', category:'Vegetables', price:  16, prevPrice:  14, unit:'kg',      state:'Tamil Nadu',       market:'Coimbatore APMC'      },
  { id: 19, name:'Snake Gourd',         emoji:'🟢', category:'Vegetables', price:  18, prevPrice:  16, unit:'kg',      state:'Kerala',           market:'Thrissur APMC'        },
  { id: 20, name:'Ash Gourd',           emoji:'⬜', category:'Vegetables', price:  10, prevPrice:   9, unit:'kg',      state:'Karnataka',        market:'Mysuru APMC'          },
  { id: 21, name:'Drumstick (Moringa)', emoji:'🌱', category:'Vegetables', price:  35, prevPrice:  30, unit:'kg',      state:'Tamil Nadu',       market:'Dindigul APMC'        },
  { id: 22, name:'Colocasia (Arbi)',    emoji:'🟤', category:'Vegetables', price:  25, prevPrice:  22, unit:'kg',      state:'Uttar Pradesh',    market:'Varanasi Mandi'       },
  { id: 23, name:'Radish',              emoji:'🔴', category:'Vegetables', price:  12, prevPrice:  10, unit:'kg',      state:'Punjab',           market:'Amritsar APMC'        },
  { id: 24, name:'Turnip',              emoji:'🟣', category:'Vegetables', price:  14, prevPrice:  12, unit:'kg',      state:'Punjab',           market:'Ludhiana Mandi'       },
  { id: 25, name:'Sweet Potato',        emoji:'🟠', category:'Vegetables', price:  22, prevPrice:  20, unit:'kg',      state:'Odisha',           market:'Bhubaneswar Mandi'    },
  { id: 26, name:'Yam (Suran)',         emoji:'🟤', category:'Vegetables', price:  30, prevPrice:  28, unit:'kg',      state:'Maharashtra',      market:'Nagpur APMC'          },
  { id: 27, name:'Fenugreek (Methi)',   emoji:'🌿', category:'Vegetables', price:  20, prevPrice:  18, unit:'bunch',   state:'Rajasthan',        market:'Jaipur Mandi'         },
  { id: 28, name:'Amaranth (Chaulai)',  emoji:'🍃', category:'Vegetables', price:  15, prevPrice:  13, unit:'bunch',   state:'Maharashtra',      market:'Mumbai APMC'          },
  { id: 29, name:'Cluster Beans (Guar)',emoji:'💚', category:'Vegetables', price:  28, prevPrice:  24, unit:'kg',      state:'Rajasthan',        market:'Barmer Mandi'         },
  { id: 30, name:'Flat Bean (Sem)',     emoji:'🟢', category:'Vegetables', price:  32, prevPrice:  28, unit:'kg',      state:'Maharashtra',      market:'Pune APMC'            },
  { id: 31, name:'Broccoli',            emoji:'🥦', category:'Vegetables', price:  55, prevPrice:  50, unit:'kg',      state:'Himachal Pradesh', market:'Shimla Mandi'         },
  { id: 32, name:'Celery',              emoji:'🌿', category:'Vegetables', price:  45, prevPrice:  40, unit:'kg',      state:'Punjab',           market:'Ludhiana Mandi'       },
  { id: 33, name:'Leek',                emoji:'🌱', category:'Vegetables', price:  60, prevPrice:  55, unit:'kg',      state:'Himachal Pradesh', market:'Kullu Mandi'          },
  { id: 34, name:'Lettuce',             emoji:'🥬', category:'Vegetables', price:  40, prevPrice:  35, unit:'kg',      state:'Maharashtra',      market:'Pune APMC'            },
  { id: 35, name:'Baby Corn',           emoji:'🌽', category:'Vegetables', price:  50, prevPrice:  45, unit:'kg',      state:'Uttar Pradesh',    market:'Lucknow Mandi'        },
  { id: 36, name:'Mushroom (Button)',   emoji:'🍄', category:'Vegetables', price:  90, prevPrice:  80, unit:'kg',      state:'Himachal Pradesh', market:'Solan Mandi'          },
  { id: 37, name:'Mushroom (Oyster)',   emoji:'🍄', category:'Vegetables', price: 110, prevPrice: 100, unit:'kg',      state:'Punjab',           market:'Ludhiana Mandi'       },
  { id: 38, name:'Zucchini',            emoji:'🟩', category:'Vegetables', price:  40, prevPrice:  35, unit:'kg',      state:'Karnataka',        market:'Bengaluru APMC'       },
  { id: 39, name:'Cherry Tomato',       emoji:'🍒', category:'Vegetables', price:  65, prevPrice:  58, unit:'kg',      state:'Maharashtra',      market:'Pune APMC'            },
  { id: 40, name:'Green Chilli',        emoji:'🌶️', category:'Vegetables', price:  30, prevPrice:  25, unit:'kg',      state:'Andhra Pradesh',   market:'Guntur APMC'          },

  // ═══════════════════ FRUITS ═══════════════════════════════════════════════
  { id: 41, name:'Mango (Alphonso)',    emoji:'🥭', category:'Fruits',     price: 180, prevPrice: 155, unit:'kg',      state:'Maharashtra',      market:'Pen APMC'             },
  { id: 42, name:'Mango (Desi)',        emoji:'🥭', category:'Fruits',     price:  55, prevPrice:  48, unit:'kg',      state:'Andhra Pradesh',   market:'Tirupati APMC'        },
  { id: 43, name:'Banana',             emoji:'🍌', category:'Fruits',     price:  22, prevPrice:  24, unit:'dozen',   state:'Tamil Nadu',       market:'Chennai APMC'         },
  { id: 44, name:'Apple (Himachali)',   emoji:'🍎', category:'Fruits',     price: 110, prevPrice: 105, unit:'kg',      state:'Himachal Pradesh', market:'Shimla Mandi'         },
  { id: 45, name:'Apple (Kashmiri)',    emoji:'🍎', category:'Fruits',     price: 130, prevPrice: 120, unit:'kg',      state:'Jammu & Kashmir',  market:'Sopore APMC'          },
  { id: 46, name:'Grapes (Green)',      emoji:'🍇', category:'Fruits',     price:  60, prevPrice:  55, unit:'kg',      state:'Maharashtra',      market:'Nashik APMC'          },
  { id: 47, name:'Grapes (Black)',      emoji:'🫐', category:'Fruits',     price:  75, prevPrice:  70, unit:'kg',      state:'Maharashtra',      market:'Sangli APMC'          },
  { id: 48, name:'Watermelon',          emoji:'🍉', category:'Fruits',     price:  15, prevPrice:  18, unit:'kg',      state:'Karnataka',        market:'Davangere Mandi'      },
  { id: 49, name:'Papaya',              emoji:'🍈', category:'Fruits',     price:  22, prevPrice:  20, unit:'kg',      state:'Andhra Pradesh',   market:'Guntur APMC'          },
  { id: 50, name:'Guava',               emoji:'🍐', category:'Fruits',     price:  30, prevPrice:  28, unit:'kg',      state:'Uttar Pradesh',    market:'Allahabad Mandi'      },
  { id: 51, name:'Pomegranate',         emoji:'🫐', category:'Fruits',     price:  85, prevPrice:  78, unit:'kg',      state:'Maharashtra',      market:'Solapur APMC'         },
  { id: 52, name:'Lemon',               emoji:'🍋', category:'Fruits',     price:  40, prevPrice:  35, unit:'kg',      state:'Andhra Pradesh',   market:'Nellore APMC'         },
  { id: 53, name:'Coconut',             emoji:'🥥', category:'Fruits',     price:   8, prevPrice:   7, unit:'piece',   state:'Kerala',           market:'Thrissur APMC'        },
  { id: 54, name:'Pineapple',           emoji:'🍍', category:'Fruits',     price:  35, prevPrice:  32, unit:'piece',   state:'Kerala',           market:'Ernakulam APMC'       },
  { id: 55, name:'Sweet Lime (Mosambi)',emoji:'🍊', category:'Fruits',     price:  45, prevPrice:  40, unit:'kg',      state:'Maharashtra',      market:'Nagpur APMC'          },
  { id: 56, name:'Orange',              emoji:'🍊', category:'Fruits',     price:  50, prevPrice:  45, unit:'kg',      state:'Maharashtra',      market:'Nagpur APMC'          },
  { id: 57, name:'Strawberry',          emoji:'🍓', category:'Fruits',     price: 120, prevPrice: 110, unit:'kg',      state:'Maharashtra',      market:'Mahabaleshwar APMC'   },
  { id: 58, name:'Kiwi',                emoji:'🥝', category:'Fruits',     price: 150, prevPrice: 140, unit:'kg',      state:'Himachal Pradesh', market:'Shimla Mandi'         },
  { id: 59, name:'Avocado',             emoji:'🥑', category:'Fruits',     price: 200, prevPrice: 185, unit:'kg',      state:'Tamil Nadu',       market:'Nilgiris APMC'        },
  { id: 60, name:'Dragon Fruit',        emoji:'🐉', category:'Fruits',     price: 180, prevPrice: 165, unit:'kg',      state:'Gujarat',          market:'Kutch APMC'           },
  { id: 61, name:'Sapota (Chikoo)',     emoji:'🟤', category:'Fruits',     price:  35, prevPrice:  30, unit:'kg',      state:'Gujarat',          market:'Surat APMC'           },
  { id: 62, name:'Custard Apple',       emoji:'💚', category:'Fruits',     price:  55, prevPrice:  50, unit:'kg',      state:'Maharashtra',      market:'Pune APMC'            },
  { id: 63, name:'Jackfruit',           emoji:'🟡', category:'Fruits',     price:  20, prevPrice:  18, unit:'kg',      state:'Kerala',           market:'Kollam APMC'          },
  { id: 64, name:'Litchi',              emoji:'🍒', category:'Fruits',     price:  80, prevPrice:  72, unit:'kg',      state:'Bihar',            market:'Muzaffarpur Mandi'    },
  { id: 65, name:'Plum',                emoji:'🫐', category:'Fruits',     price:  70, prevPrice:  65, unit:'kg',      state:'Himachal Pradesh', market:'Kullu Mandi'          },
  { id: 66, name:'Peach',               emoji:'🍑', category:'Fruits',     price:  75, prevPrice:  68, unit:'kg',      state:'Himachal Pradesh', market:'Shimla Mandi'         },
  { id: 67, name:'Pear',                emoji:'🍐', category:'Fruits',     price:  65, prevPrice:  60, unit:'kg',      state:'Jammu & Kashmir',  market:'Srinagar Mandi'       },
  { id: 68, name:'Fig (Anjeer)',         emoji:'🟣', category:'Fruits',     price: 250, prevPrice: 230, unit:'kg',      state:'Maharashtra',      market:'Pune APMC'            },
  { id: 69, name:'Dates',               emoji:'🟤', category:'Fruits',     price: 180, prevPrice: 170, unit:'kg',      state:'Rajasthan',        market:'Barmer Mandi'         },
  { id: 70, name:'Tamarind',            emoji:'🟤', category:'Fruits',     price:  60, prevPrice:  55, unit:'kg',      state:'Andhra Pradesh',   market:'Kurnool APMC'         },
  { id: 71, name:'Amla (Gooseberry)',   emoji:'🟢', category:'Fruits',     price:  25, prevPrice:  22, unit:'kg',      state:'Uttar Pradesh',    market:'Pratapgarh Mandi'     },
  { id: 72, name:'Wood Apple (Bael)',   emoji:'🟡', category:'Fruits',     price:  30, prevPrice:  28, unit:'kg',      state:'Uttar Pradesh',    market:'Varanasi Mandi'       },
  { id: 73, name:'Passion Fruit',       emoji:'🟣', category:'Fruits',     price: 160, prevPrice: 145, unit:'kg',      state:'Karnataka',        market:'Coorg APMC'           },
  { id: 74, name:'Star Fruit',          emoji:'⭐', category:'Fruits',     price:  90, prevPrice:  82, unit:'kg',      state:'Kerala',           market:'Ernakulam APMC'       },
  { id: 75, name:'Mulberry',            emoji:'🫐', category:'Fruits',     price:  80, prevPrice:  72, unit:'kg',      state:'Karnataka',        market:'Bengaluru APMC'       },
  { id: 76, name:'Jamun (Black Plum)',  emoji:'🟣', category:'Fruits',     price:  45, prevPrice:  40, unit:'kg',      state:'Uttar Pradesh',    market:'Lucknow Mandi'        },
  { id: 77, name:'Ber (Jujube)',        emoji:'🟤', category:'Fruits',     price:  30, prevPrice:  27, unit:'kg',      state:'Rajasthan',        market:'Jaipur Mandi'         },

  // ═══════════════════ FLOWERS ══════════════════════════════════════════════
  { id: 78, name:'Rose (Red)',           emoji:'🌹', category:'Flowers',    price: 120, prevPrice: 100, unit:'100 pcs', state:'Tamil Nadu',       market:'Hosur Flower Market'  },
  { id: 79, name:'Rose (White)',         emoji:'🤍', category:'Flowers',    price:  90, prevPrice:  80, unit:'100 pcs', state:'Karnataka',        market:'Bengaluru Flower Mkt' },
  { id: 80, name:'Marigold (Yellow)',    emoji:'🌼', category:'Flowers',    price:  25, prevPrice:  20, unit:'kg',      state:'Maharashtra',      market:'Pune APMC'            },
  { id: 81, name:'Marigold (Orange)',    emoji:'🌼', category:'Flowers',    price:  28, prevPrice:  22, unit:'kg',      state:'Karen',            market:'Tamil Nadu APMC'      },
  { id: 82, name:'Jasmine',             emoji:'🌸', category:'Flowers',    price: 200, prevPrice: 180, unit:'kg',      state:'Tamil Nadu',       market:'Madurai APMC'         },
  { id: 83, name:'Chrysanthemum',       emoji:'🌺', category:'Flowers',    price:  40, prevPrice:  35, unit:'kg',      state:'Karnataka',        market:'Bengaluru Flower Mkt' },
  { id: 84, name:'Lotus',               emoji:'🪷', category:'Flowers',    price:  60, prevPrice:  55, unit:'100 pcs', state:'Andhra Pradesh',   market:'Vijayawada APMC'      },
  { id: 85, name:'Tuberose (Rajnigandha)',emoji:'🌾',category:'Flowers',   price:  80, prevPrice:  70, unit:'kg',      state:'Maharashtra',      market:'Pune APMC'            },
  { id: 86, name:'Gerbera',             emoji:'🌻', category:'Flowers',    price: 180, prevPrice: 160, unit:'100 pcs', state:'Karnataka',        market:'Bengaluru Flower Mkt' },
  { id: 87, name:'Sunflower (Cut)',      emoji:'🌻', category:'Flowers',    price:  35, prevPrice:  30, unit:'bunch',   state:'Karnataka',        market:'Bidar Mandi'          },
  { id: 88, name:'Orchid',              emoji:'💜', category:'Flowers',    price: 350, prevPrice: 320, unit:'100 pcs', state:'West Bengal',      market:'Kolkata Flower Mkt'   },
  { id: 89, name:'Gladiolus',           emoji:'🌷', category:'Flowers',    price: 250, prevPrice: 220, unit:'100 pcs', state:'Himachal Pradesh', market:'Solan Flower Market'  },
  { id: 90, name:'Carnation',           emoji:'🌸', category:'Flowers',    price: 160, prevPrice: 145, unit:'100 pcs', state:'Karnataka',        market:'Bengaluru Flower Mkt' },
  { id: 91, name:'Lily',                emoji:'🌷', category:'Flowers',    price: 200, prevPrice: 180, unit:'100 pcs', state:'West Bengal',      market:'Kolkata Flower Mkt'   },
  { id: 92, name:'Dahlia',              emoji:'🌺', category:'Flowers',    price:  50, prevPrice:  44, unit:'kg',      state:'Himachal Pradesh', market:'Shimla Mandi'         },
  { id: 93, name:'Lavender',            emoji:'💜', category:'Flowers',    price: 400, prevPrice: 370, unit:'kg',      state:'Jammu & Kashmir',  market:'Pulwama Mandi'        },
  { id: 94, name:'Bird of Paradise',    emoji:'🦜', category:'Flowers',    price: 300, prevPrice: 275, unit:'100 pcs', state:'Karnataka',        market:'Bengaluru Flower Mkt' },
  { id: 95, name:'Anthurium',           emoji:'❤️',  category:'Flowers',    price: 450, prevPrice: 420, unit:'100 pcs', state:'Kerala',           market:'Ernakulam APMC'       },
  { id: 96, name:'Aster',               emoji:'🌸', category:'Flowers',    price:  70, prevPrice:  62, unit:'kg',      state:'Tamil Nadu',       market:'Hosur Flower Market'  },
  { id: 97, name:'Zinnia',              emoji:'🌺', category:'Flowers',    price:  35, prevPrice:  30, unit:'kg',      state:'Maharashtra',      market:'Nashik APMC'          },
  { id: 98, name:'Pansy',               emoji:'🌸', category:'Flowers',    price: 120, prevPrice: 110, unit:'100 pcs', state:'Himachal Pradesh', market:'Shimla Mandi'         },
  { id: 99, name:'Peony',               emoji:'🌸', category:'Flowers',    price: 500, prevPrice: 460, unit:'100 pcs', state:'Jammu & Kashmir',  market:'Srinagar Mandi'       },
  { id:100, name:'Hibiscus',            emoji:'🌺', category:'Flowers',    price:  45, prevPrice:  40, unit:'kg',      state:'Kerala',           market:'Thrissur APMC'        },

  // ═══════════════════ GRAINS ═══════════════════════════════════════════════
  { id:101, name:'Wheat',               emoji:'🌾', category:'Grains',     price:2350, prevPrice:2300, unit:'quintal', state:'Punjab',           market:'Ludhiana Mandi'       },
  { id:102, name:'Rice (Basmati)',       emoji:'🍚', category:'Grains',     price:4800, prevPrice:4750, unit:'quintal', state:'Haryana',          market:'Karnal APMC'          },
  { id:103, name:'Rice (Common)',        emoji:'🍚', category:'Grains',     price:2400, prevPrice:2350, unit:'quintal', state:'West Bengal',      market:'Kolkata APMC'         },
  { id:104, name:'Maize (Corn)',         emoji:'🌽', category:'Grains',     price:1650, prevPrice:1700, unit:'quintal', state:'Karnataka',        market:'Davangere Mandi'      },
  { id:105, name:'Jowar (Sorghum)',      emoji:'🟡', category:'Grains',     price:2200, prevPrice:2100, unit:'quintal', state:'Maharashtra',      market:'Latur Mandi'          },
  { id:106, name:'Bajra (Pearl Millet)', emoji:'🟤', category:'Grains',     price:1900, prevPrice:1850, unit:'quintal', state:'Rajasthan',        market:'Barmer Mandi'         },
  { id:107, name:'Ragi (Finger Millet)', emoji:'🟫', category:'Grains',     price:2800, prevPrice:2700, unit:'quintal', state:'Karnataka',        market:'Hassan Mandi'         },
  { id:108, name:'Barley',              emoji:'🌾', category:'Grains',     price:1600, prevPrice:1550, unit:'quintal', state:'Haryana',          market:'Ambala Mandi'         },
  { id:109, name:'Oats',                emoji:'🌾', category:'Grains',     price:2100, prevPrice:2050, unit:'quintal', state:'Punjab',           market:'Amritsar APMC'        },
  { id:110, name:'Sorghum',             emoji:'🟡', category:'Grains',     price:2300, prevPrice:2200, unit:'quintal', state:'Maharashtra',      market:'Aurangabad Mandi'     },
  { id:111, name:'Foxtail Millet (Kakum)',emoji:'🌾',category:'Grains',    price:3200, prevPrice:3100, unit:'quintal', state:'Andhra Pradesh',   market:'Nellore APMC'         },
  { id:112, name:'Kodo Millet',         emoji:'🌾', category:'Grains',     price:3000, prevPrice:2900, unit:'quintal', state:'Madhya Pradesh',   market:'Balaghat Mandi'       },
  { id:113, name:'Little Millet',       emoji:'🌾', category:'Grains',     price:3500, prevPrice:3400, unit:'quintal', state:'Karnataka',        market:'Bellary Mandi'        },
  { id:114, name:'Buckwheat (Kuttu)',    emoji:'🟤', category:'Grains',     price:4500, prevPrice:4300, unit:'quintal', state:'Himachal Pradesh', market:'Shimla Mandi'         },
  { id:115, name:'Quinoa',              emoji:'⚪', category:'Grains',     price:8000, prevPrice:7800, unit:'quintal', state:'Rajasthan',        market:'Jaipur Mandi'         },
  { id:116, name:'Amaranth (Rajgira)',   emoji:'🔴', category:'Grains',     price:5500, prevPrice:5300, unit:'quintal', state:'Maharashtra',      market:'Pune APMC'            },

  // ═══════════════════ PULSES ═══════════════════════════════════════════════
  { id:117, name:'Chickpea (Chana)',     emoji:'🟤', category:'Pulses',     price:5400, prevPrice:5500, unit:'quintal', state:'Rajasthan',        market:'Jaipur Mandi'         },
  { id:118, name:'Soybean',             emoji:'🟩', category:'Pulses',     price:4200, prevPrice:4100, unit:'quintal', state:'Madhya Pradesh',   market:'Indore Mandi'         },
  { id:119, name:'Pigeon Pea (Tur/Arhar)',emoji:'🟫',category:'Pulses',    price:6200, prevPrice:6000, unit:'quintal', state:'Maharashtra',      market:'Latur Mandi'          },
  { id:120, name:'Lentil (Masoor)',      emoji:'🔴', category:'Pulses',     price:5600, prevPrice:5500, unit:'quintal', state:'Madhya Pradesh',   market:'Jabalpur Mandi'       },
  { id:121, name:'Green Gram (Moong)',   emoji:'🟢', category:'Pulses',     price:7200, prevPrice:7000, unit:'quintal', state:'Rajasthan',        market:'Bikaner Mandi'        },
  { id:122, name:'Black Gram (Urad)',    emoji:'⚫', category:'Pulses',     price:6800, prevPrice:6900, unit:'quintal', state:'Andhra Pradesh',   market:'Kurnool APMC'         },
  { id:123, name:'Kidney Bean (Rajma)',  emoji:'🔴', category:'Pulses',     price:8500, prevPrice:8200, unit:'quintal', state:'Himachal Pradesh', market:'Shimla Mandi'         },
  { id:124, name:'Field Pea (Matar)',    emoji:'🟢', category:'Pulses',     price:4000, prevPrice:3900, unit:'quintal', state:'Uttar Pradesh',    market:'Agra Mandi'           },
  { id:125, name:'Horse Gram (Kulthi)',  emoji:'🟤', category:'Pulses',     price:5000, prevPrice:4800, unit:'quintal', state:'Tamil Nadu',       market:'Vellore APMC'         },
  { id:126, name:'Lima Bean (Sem)',      emoji:'🟢', category:'Pulses',     price:4500, prevPrice:4300, unit:'quintal', state:'Maharashtra',      market:'Nashik APMC'          },
  { id:127, name:'Cowpea (Lobia)',       emoji:'⚫', category:'Pulses',     price:5800, prevPrice:5600, unit:'quintal', state:'Karnataka',        market:'Gulbarga Mandi'       },
  { id:128, name:'Moth Bean',           emoji:'🟤', category:'Pulses',     price:5200, prevPrice:5000, unit:'quintal', state:'Rajasthan',        market:'Jodhpur Mandi'        },
  { id:129, name:'Dolichos Bean (Val)', emoji:'🟢', category:'Pulses',     price:4800, prevPrice:4600, unit:'quintal', state:'Gujarat',          market:'Surat APMC'           },
  { id:130, name:'Chickpea (Kabuli)',    emoji:'⚪', category:'Pulses',     price:7500, prevPrice:7200, unit:'quintal', state:'Madhya Pradesh',   market:'Indore Mandi'         },

  // ═══════════════════ SPICES ═══════════════════════════════════════════════
  { id:131, name:'Chilli (Dry)',         emoji:'🌶️', category:'Spices',     price: 125, prevPrice: 140, unit:'kg',      state:'Andhra Pradesh',   market:'Guntur APMC'          },
  { id:132, name:'Turmeric',            emoji:'🟡', category:'Spices',     price:  95, prevPrice:  88, unit:'kg',      state:'Tamil Nadu',       market:'Erode APMC'           },
  { id:133, name:'Ginger (Dry)',         emoji:'🟡', category:'Spices',     price: 180, prevPrice: 165, unit:'kg',      state:'Kerala',           market:'Kozhikode APMC'       },
  { id:134, name:'Cardamom',            emoji:'💚', category:'Spices',     price:1800, prevPrice:1650, unit:'kg',      state:'Kerala',           market:'Kumily APMC'          },
  { id:135, name:'Black Pepper',        emoji:'⚫', category:'Spices',     price: 650, prevPrice: 600, unit:'kg',      state:'Kerala',           market:'Calicut APMC'         },
  { id:136, name:'Coriander (Seeds)',    emoji:'🟢', category:'Spices',     price:  65, prevPrice:  60, unit:'kg',      state:'Rajasthan',        market:'Ramganj Mandi'        },
  { id:137, name:'Cumin (Jeera)',        emoji:'🟤', category:'Spices',     price: 280, prevPrice: 260, unit:'kg',      state:'Rajasthan',        market:'Unjha APMC'           },
  { id:138, name:'Fennel (Saunf)',       emoji:'🌱', category:'Spices',     price: 120, prevPrice: 110, unit:'kg',      state:'Gujarat',          market:'Unjha APMC'           },
  { id:139, name:'Ajwain (Carom)',       emoji:'⚪', category:'Spices',     price:  95, prevPrice:  90, unit:'kg',      state:'Rajasthan',        market:'Nagaur Mandi'         },
  { id:140, name:'Clove',               emoji:'🟤', category:'Spices',     price:1100, prevPrice:1050, unit:'kg',      state:'Kerala',           market:'Kozhikode APMC'       },
  { id:141, name:'Cinnamon',            emoji:'🟫', category:'Spices',     price: 350, prevPrice: 325, unit:'kg',      state:'Tamil Nadu',       market:'Kanyakumari APMC'     },
  { id:142, name:'Nutmeg',              emoji:'🟤', category:'Spices',     price: 800, prevPrice: 750, unit:'kg',      state:'Kerala',           market:'Ernakulam APMC'       },
  { id:143, name:'Star Anise',          emoji:'⭐', category:'Spices',     price: 400, prevPrice: 380, unit:'kg',      state:'Arunachal Pradesh',market:'Itanagar Mandi'       },
  { id:144, name:'Bay Leaf (Tej Patta)',emoji:'🍃', category:'Spices',     price: 120, prevPrice: 110, unit:'kg',      state:'Uttarakhand',      market:'Dehradun Mandi'       },
  { id:145, name:'Fenugreek (Seeds)',   emoji:'🟡', category:'Spices',     price:  75, prevPrice:  68, unit:'kg',      state:'Rajasthan',        market:'Sojat Mandi'          },
  { id:146, name:'Mustard Seeds',       emoji:'⚫', category:'Spices',     price:  55, prevPrice:  50, unit:'kg',      state:'Rajasthan',        market:'Bharatpur Mandi'      },
  { id:147, name:'Saffron (Kesar)',      emoji:'🟠', category:'Spices',     price:250000,prevPrice:240000,unit:'kg',    state:'Jammu & Kashmir',  market:'Pampore Mandi'        },
  { id:148, name:'Vanilla',             emoji:'🟤', category:'Spices',     price:45000,prevPrice:42000, unit:'kg',     state:'Kerala',           market:'Ernakulam APMC'       },
  { id:149, name:'Asafoetida (Hing)',   emoji:'🟡', category:'Spices',     price:2200, prevPrice:2100, unit:'kg',      state:'Rajasthan',        market:'Jaipur Mandi'         },
  { id:150, name:'Kalonji (Nigella)',    emoji:'⚫', category:'Spices',     price: 145, prevPrice: 135, unit:'kg',      state:'Madhya Pradesh',   market:'Neemuch Mandi'        },

  // ═══════════════════ CASH CROPS ═══════════════════════════════════════════
  { id:151, name:'Cotton (Kapas)',       emoji:'🌿', category:'Cash Crops', price:6800, prevPrice:6600, unit:'quintal', state:'Gujarat',          market:'Rajkot APMC'          },
  { id:152, name:'Sugarcane',           emoji:'🎋', category:'Cash Crops', price: 310, prevPrice: 305, unit:'quintal', state:'Uttar Pradesh',    market:'Muzaffarnagar Mandi'  },
  { id:153, name:'Jute',                emoji:'🟫', category:'Cash Crops', price:4500, prevPrice:4300, unit:'quintal', state:'West Bengal',      market:'Kolkata APMC'         },
  { id:154, name:'Tobacco (Flue-Cured)',emoji:'🍃', category:'Cash Crops', price: 180, prevPrice: 170, unit:'kg',      state:'Andhra Pradesh',   market:'Guntur APMC'          },
  { id:155, name:'Tea (Green Leaf)',     emoji:'🍃', category:'Cash Crops', price:  18, prevPrice:  16, unit:'kg',      state:'Assam',            market:'Jorhat APMC'          },
  { id:156, name:'Coffee (Arabica)',     emoji:'☕', category:'Cash Crops', price: 380, prevPrice: 360, unit:'kg',      state:'Karnataka',        market:'Chikkamagaluru APMC'  },
  { id:157, name:'Coffee (Robusta)',     emoji:'☕', category:'Cash Crops', price: 280, prevPrice: 265, unit:'kg',      state:'Kerala',           market:'Wayanad APMC'         },
  { id:158, name:'Rubber',              emoji:'⚪', category:'Cash Crops', price: 155, prevPrice: 148, unit:'kg',      state:'Kerala',           market:'Kottayam APMC'        },
  { id:159, name:'Coconut Coir',        emoji:'🟤', category:'Cash Crops', price:  12, prevPrice:  10, unit:'kg',      state:'Kerala',           market:'Alappuzha APMC'       },
  { id:160, name:'Betel Nut (Supari)',  emoji:'🟤', category:'Cash Crops', price: 380, prevPrice: 360, unit:'kg',      state:'Karnataka',        market:'Sirsi APMC'           },
  { id:161, name:'Indigo',              emoji:'🔵', category:'Cash Crops', price: 450, prevPrice: 430, unit:'kg',      state:'Rajasthan',        market:'Jaipur Mandi'         },
  { id:162, name:'Banana (Fibre)',       emoji:'🌿', category:'Cash Crops', price:  25, prevPrice:  22, unit:'kg',      state:'Tamil Nadu',       market:'Thanjavur APMC'       },
  { id:163, name:'Hemp (Industrial)',    emoji:'🌿', category:'Cash Crops', price: 800, prevPrice: 750, unit:'kg',      state:'Uttarakhand',      market:'Dehradun Mandi'       },
  { id:164, name:'Silk Cocoon',         emoji:'⚪', category:'Cash Crops', price: 320, prevPrice: 300, unit:'kg',      state:'Karnataka',        market:'Mysuru APMC'          },

  // ═══════════════════ OILSEEDS ══════════════════════════════════════════════
  { id:165, name:'Mustard (Sarson)',     emoji:'🟡', category:'Oilseeds',   price:5100, prevPrice:5000, unit:'quintal', state:'Rajasthan',        market:'Bharatpur Mandi'      },
  { id:166, name:'Groundnut (Moongfali)',emoji:'🥜', category:'Oilseeds',   price:5800, prevPrice:5600, unit:'quintal', state:'Gujarat',          market:'Junagadh APMC'        },
  { id:167, name:'Sesame (Til)',         emoji:'⚪', category:'Oilseeds',   price:8500, prevPrice:8200, unit:'quintal', state:'Rajasthan',        market:'Sojat Mandi'          },
  { id:168, name:'Sunflower Seed',       emoji:'🌻', category:'Oilseeds',   price:5200, prevPrice:5100, unit:'quintal', state:'Karnataka',        market:'Bidar Mandi'          },
  { id:169, name:'Castor',              emoji:'🟤', category:'Oilseeds',   price:5900, prevPrice:5700, unit:'quintal', state:'Gujarat',          market:'Deesa APMC'           },
  { id:170, name:'Linseed (Alsi)',       emoji:'🔵', category:'Oilseeds',   price:5600, prevPrice:5400, unit:'quintal', state:'Madhya Pradesh',   market:'Hoshangabad Mandi'    },
  { id:171, name:'Niger Seed (Ramtil)',  emoji:'⚫', category:'Oilseeds',   price:6200, prevPrice:6000, unit:'quintal', state:'Chhattisgarh',     market:'Raipur Mandi'         },
  { id:172, name:'Safflower (Kardi)',    emoji:'🟠', category:'Oilseeds',   price:5500, prevPrice:5300, unit:'quintal', state:'Maharashtra',      market:'Latur Mandi'          },
  { id:173, name:'Palm Oil (Crude)',     emoji:'🟠', category:'Oilseeds',   price:8800, prevPrice:8600, unit:'quintal', state:'Telangana',        market:'Warangal APMC'        },
  { id:174, name:'Coconut (Copra)',      emoji:'🥥', category:'Oilseeds',   price:11500,prevPrice:11000,unit:'quintal', state:'Kerala',           market:'Thrissur APMC'        },
  { id:175, name:'Hemp Seed',           emoji:'🌿', category:'Oilseeds',   price:9000, prevPrice:8700, unit:'quintal', state:'Uttarakhand',      market:'Dehradun Mandi'       },
  { id:176, name:'Chia Seed',           emoji:'⚫', category:'Oilseeds',   price:15000,prevPrice:14500,unit:'quintal', state:'Rajasthan',        market:'Jaipur Mandi'         },

  // ═══════════════════ HERBS & DAIRY ════════════════════════════════════════
  { id:177, name:'Tulsi (Holy Basil)',   emoji:'🌿', category:'Herbs & Dairy', price: 120, prevPrice: 100, unit:'kg',    state:'Uttar Pradesh',    market:'Lucknow Mandi'        },
  { id:178, name:'Mint (Pudina)',        emoji:'🍃', category:'Herbs & Dairy', price:  40, prevPrice:  35, unit:'kg',    state:'Uttar Pradesh',    market:'Barabanki Mandi'      },
  { id:179, name:'Lemongrass',          emoji:'🌱', category:'Herbs & Dairy', price:  25, prevPrice:  22, unit:'kg',    state:'Madhya Pradesh',   market:'Mandsaur Mandi'       },
  { id:180, name:'Milk (Buffalo)',       emoji:'🧈', category:'Herbs & Dairy', price:  52, prevPrice:  50, unit:'litre', state:'Rajasthan',        market:'Jaipur Dairy'         },
  { id:181, name:'Milk (Cow)',           emoji:'🥛', category:'Herbs & Dairy', price:  42, prevPrice:  40, unit:'litre', state:'Gujarat',          market:'Anand Dairy'          },
  { id:182, name:'Honey (Wild)',         emoji:'🍯', category:'Herbs & Dairy', price: 450, prevPrice: 420, unit:'kg',    state:'Uttarakhand',      market:'Dehradun Mandi'       },
  { id:183, name:'Honey (Processed)',    emoji:'🍯', category:'Herbs & Dairy', price: 320, prevPrice: 300, unit:'kg',    state:'Maharashtra',      market:'Satara APMC'          },
  { id:184, name:'Aloe Vera',           emoji:'🌵', category:'Herbs & Dairy', price:  15, prevPrice:  13, unit:'kg',    state:'Rajasthan',        market:'Jodhpur Mandi'        },
  { id:185, name:'Brahmi',              emoji:'🌿', category:'Herbs & Dairy', price:  80, prevPrice:  72, unit:'kg',    state:'Bihar',            market:'Patna Mandi'          },
  { id:186, name:'Ashwagandha',         emoji:'🌿', category:'Herbs & Dairy', price: 160, prevPrice: 145, unit:'kg',    state:'Rajasthan',        market:'Nagaur Mandi'         },
  { id:187, name:'Stevia',              emoji:'🌱', category:'Herbs & Dairy', price: 200, prevPrice: 182, unit:'kg',    state:'Maharashtra',      market:'Pune APMC'            },
  { id:188, name:'Giloy',               emoji:'🌿', category:'Herbs & Dairy', price:  55, prevPrice:  48, unit:'kg',    state:'Uttar Pradesh',    market:'Lucknow Mandi'        },
  { id:189, name:'Shatavari',           emoji:'🌱', category:'Herbs & Dairy', price: 180, prevPrice: 165, unit:'kg',    state:'Rajasthan',        market:'Pali Mandi'           },
  { id:190, name:'Neem Leaf',           emoji:'🍃', category:'Herbs & Dairy', price:  20, prevPrice:  18, unit:'kg',    state:'Maharashtra',      market:'Nagpur APMC'          },
  { id:191, name:'Curry Leaf',          emoji:'🍃', category:'Herbs & Dairy', price:  35, prevPrice:  30, unit:'kg',    state:'Tamil Nadu',       market:'Krishna Mandi'        },
  { id:192, name:'Rosemary',            emoji:'🌿', category:'Herbs & Dairy', price: 250, prevPrice: 230, unit:'kg',    state:'Himachal Pradesh', market:'Shimla Mandi'         },
  { id:193, name:'Thyme',               emoji:'🌱', category:'Herbs & Dairy', price: 280, prevPrice: 260, unit:'kg',    state:'Himachal Pradesh', market:'Kullu Mandi'          },
  { id:194, name:'Oregano',             emoji:'🌿', category:'Herbs & Dairy', price: 320, prevPrice: 295, unit:'kg',    state:'Himachal Pradesh', market:'Shimla Mandi'         },
  { id:195, name:'Basil (Sweet)',        emoji:'🌿', category:'Herbs & Dairy', price: 180, prevPrice: 165, unit:'kg',    state:'Maharashtra',      market:'Pune APMC'            },
  { id:196, name:'Cow Ghee',            emoji:'🧈', category:'Herbs & Dairy', price: 620, prevPrice: 580, unit:'kg',    state:'Rajasthan',        market:'Jaipur Dairy'         },
  { id:197, name:'Paneer',              emoji:'🧀', category:'Herbs & Dairy', price: 320, prevPrice: 295, unit:'kg',    state:'Punjab',           market:'Amritsar Dairy'       },
  { id:198, name:'Curd (Dahi)',          emoji:'🥛', category:'Herbs & Dairy', price:  55, prevPrice:  50, unit:'kg',    state:'Gujarat',          market:'Anand Dairy'          },
  { id:199, name:'Butter (White)',       emoji:'🧈', category:'Herbs & Dairy', price: 480, prevPrice: 450, unit:'kg',    state:'Haryana',          market:'Karnal Dairy'         },
  { id:200, name:'Wheatgrass',          emoji:'🌱', category:'Herbs & Dairy', price: 120, prevPrice: 108, unit:'kg',    state:'Maharashtra',      market:'Pune APMC'            },
  { id:201, name:'Moringa Leaf (Powder)',emoji:'🌿',category:'Herbs & Dairy', price: 350, prevPrice: 320, unit:'kg',    state:'Tamil Nadu',       market:'Dindigul APMC'        },
  { id:202, name:'Triphala Herb',       emoji:'🌿', category:'Herbs & Dairy', price: 220, prevPrice: 200, unit:'kg',    state:'Madhya Pradesh',   market:'Jabalpur Mandi'       },

];

export default CROP_DATA;
